- id: stdlib-linter
  name: stdlib-linter
  description: stdlib-linter validates syntactic restrictions in hsecode.com/stdlib projects
  entry: stdlib-linter
  language: golang
  pass_filenames: false
  files: \.go$
- id: gofmt
  name: gofmt
  description: "Runs `gofmt`"
  entry: pygofmt
  language: python
  pass_filenames: true
  files: \.go$
- id: generate
  name: go generate
  description: "Runs `go generate` for all packages"
  entry: go generate ./...
  language: system
  pass_filenames: false
  files: \.go$
- id: no-untracked
  name: check untracked files
  description: "Prevents commits with untracked files"
  entry: pyuntracked
  language: python
  pass_filenames: false
  files: \.go$
