- id: stdlib-linter
  name: stdlib-linter
  description: stdlib-linter validates syntactic restrictions in hsecode.com/stdlib projects
  entry: stdlib-linter
  language: golang
  pass_filenames: false
  files: \.go$
- id: gofmt
  name: gofmt
  description: "Runs `gofmt`, requires golang"
  entry: misc/gofmt.sh .
  language: script
  pass_filenames: false
  files: \.go$
